flowchart TD
subgraph ENTRY_BLOCK["[ENTRY]"]
direction TB
ENTRY["GET /board/:slug/:displayId/edit"]
end
subgraph MIDDLEWARES["[MIDDLEWARES]"]
direction TB
MIDDLEWARE1["<b>[Global Middlewares]</b>"]
MIDDLEWARE2["requireAuthRedirect()"]
end
ENTRY --> MIDDLEWARE1
MIDDLEWARE1 --> MIDDLEWARE2
subgraph HANDLER_BLOCK["[HANDLER]"]
direction TB
HANDLER["getArticleEditForm()"]
end
MIDDLEWARE2 --> HANDLER
classDef middleware font-size:10px,padding:2px,stroke-width:1;
classDef diagnostics stroke-dasharray: 2 2;
classDef sink stroke-width:2;
classDef exit stroke-dasharray: 4 2;
class MIDDLEWARE1,MIDDLEWARE2 middleware;
