flowchart TD
subgraph ENTRY_BLOCK["[ENTRY]"]
direction TB
ENTRY["GET /login"]
end
subgraph MIDDLEWARES["[MIDDLEWARES]"]
direction TB
MIDDLEWARE1["<b>[Global Middlewares]</b>"]
end
ENTRY --> MIDDLEWARE1
subgraph HANDLER_BLOCK["[HANDLER]"]
direction TB
HANDLER["getLoginPage()"]
end
MIDDLEWARE1 --> HANDLER
classDef middleware font-size:10px,padding:2px,stroke-width:1;
classDef diagnostics stroke-dasharray: 2 2;
classDef sink stroke-width:2;
classDef exit stroke-dasharray: 4 2;
class MIDDLEWARE1 middleware;
