flowchart TD
subgraph ENTRY_BLOCK["[ENTRY]"]
direction TB
ENTRY["GET /board/:slug"]
end
subgraph MIDDLEWARES["[MIDDLEWARES]"]
direction TB
MIDDLEWARE1["<b>[Global Middlewares]</b>"]
end
ENTRY --> MIDDLEWARE1
subgraph HANDLER_BLOCK["[HANDLER]"]
direction TB
HANDLER["getBoardBySlug()"]
end
MIDDLEWARE1 --> HANDLER
subgraph SINKS["[SINKS]"]
direction TB
SINK1["req.session()"]
end
HANDLER --> SINK1
subgraph EXITS["[EXITS]"]
direction TB
EXIT1["res.render()"]
end
HANDLER --> EXIT1
classDef middleware font-size:10px,padding:2px,stroke-width:1;
classDef diagnostics stroke-dasharray: 2 2;
classDef sink stroke-width:2;
classDef exit stroke-dasharray: 4 2;
class MIDDLEWARE1 middleware;
class SINK1 sink;
class EXIT1 exit;
