flowchart TD
subgraph ENTRY_BLOCK["[ENTRY]"]
direction TB
ENTRY["POST /setting/profile"]
end
subgraph MIDDLEWARES["[MIDDLEWARES]"]
direction TB
MIDDLEWARE1["<b>[Global Middlewares]</b>"]
MIDDLEWARE2["requireAuthRedirect()"]
end
ENTRY --> MIDDLEWARE1
MIDDLEWARE1 --> MIDDLEWARE2
subgraph HANDLER_BLOCK["[HANDLER]"]
direction TB
HANDLER["postProfileEdit()"]
end
MIDDLEWARE2 --> HANDLER
subgraph ERROR_STATUS["[ERROR STATUS]"]
direction TB
RDIAG1["422"]
end
subgraph SINKS["[SINKS]"]
direction TB
SINK1["req.session()"]
end
HANDLER --> SINK1
subgraph EXITS["[EXITS]"]
direction TB
EXIT1["res.render()"]
EXIT2["res.redirect()"]
end
HANDLER --> EXIT1
HANDLER --> EXIT2
EXIT1 --> RDIAG1
subgraph NEXT_ENTRY["[NEXT ENTRY]"]
direction TB
NEXT_ENTRY1["/login"]
end
EXIT2 --> NEXT_ENTRY1
classDef middleware font-size:10px,padding:2px,stroke-width:1;
classDef diagnostics stroke-dasharray: 2 2;
classDef sink stroke-width:2;
classDef exit stroke-dasharray: 4 2;
class MIDDLEWARE1,MIDDLEWARE2 middleware;
class RDIAG1 diagnostics;
class SINK1 sink;
class EXIT1,EXIT2 exit;
